
---
include:
  - board: nice_nano//zmk
    shield: Lily58_left
    artifact-name: Lily58_peripheral_left_oled
  - board: nice_nano//zmk
    shield: Lily58_right
    artifact-name: Lily58_peripheral_right_oled   
  - board: xiao_ble//zmk
    shield: lily58_prospector_adapter
  - board: nice_nano//zmk
    shield: settings_reset
  - board: xiao_ble//zmk
    shield: settings_reset
  - board: nice_nano//zmk
    shield: <existing shields> raw_hid_adapter # <-- required for Raw HID support
    snippet: studio-rpc-usb-uart # <-- required for ZMK Studio support
