
---
include:
  - board: nice_nano_v2/zmk
    shield: Lily58_dongle_left
    artifact-name: Lily58_peripheral_left_oled
  - board: nice_nano_v2/zmk
    shield: Lily58_dongle_right
    artifact-name: Lily58_peripheral_right_oled   
  - board: seeeduino_xiao_ble/zmk
    shield: lily58_dongle prospector_adapter
  - board: nice_nano_v2/zmk
    shield: settings_reset
  - board: seeeduino_xiao_ble/zmk
    shield: settings_reset
  - board: nice_nano_v2/zmk
    shield: <existing shields> raw_hid_adapter # <-- required for Raw HID support
    snippet: studio-rpc-usb-uart # <-- required for ZMK Studio support
